name: Deploy Demo Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
    - run: npm run build
    - run: npm install -g surge
    - run: surge --domain unofficial-observablehq-compiler-demo.surge.sh --project .
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
